In [1]:
import pandas as pd
import numpy as np

In [2]:
%%time

data = pd.read_csv("hyderabad.csv")
data.shape

Wall time: 542 ms

<decorator-gen-55>:2: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.

(18900, 35)

In [3]:
data.head()

,active,amenities,balconies,bathroom,combineDescription,completeStreetName,deposit,facing,facingDesc,floor,...,property_age,reactivationSource,rent_amount,sharedAccomodation,shortUrl,swimmingPool,totalFloor,type_bhk,waterSupply,weight
0,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",2,2,NaN,"Ramakrishna Nagar, near Reliance Trends",30000,W,West,1,...,5,MISSED_CALL,15000,False,http://nobr.kr/sv/Q4CVh,False,4,BHK3,CORP_BORE,NaN
1,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",1,3,NaN,"Hilltop Colony, Padmavathi Nagar, Khairatabad,...",90000,S,South,1,...,5,USER_DASHBOARD,30000,False,http://nobr.kr/sv/6bGnh,False,5,BHK3,CORP_BORE,NaN
2,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",2,2,NaN,"Phase 1 , near Srikara Hospitals - Miyapur",50000,N,North,2,...,1,None,18000,False,http://nobr.kr/sv/P2TNg,False,4,BHK2,CORP_BORE,NaN
3,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":true,""AC"":...",1,2,NaN,"Near NCB Enclave, Kondapur Main Road, Kondapur...",30000,E,East,5,...,5,None,30000,False,http://nobr.kr/sv/jW8vh,False,5,BHK3,CORP_BORE,NaN
4,True,"{""LIFT"":true,""GYM"":false,""INTERNET"":false,""AC""...",1,2,NaN,"No.350/5&6, Jawahar Nagar, Vasanth Vihar Colon...",17000,W,West,3,...,5,PROPERTY_DASHBOARD,17000,False,http://nobr.kr/sv/ZnjPh,False,6,BHK3,CORP_BORE,NaN

In [4]:
data.isnull().sum()

active                    0
amenities                 0
balconies                 0
bathroom                  0
combineDescription    18900
completeStreetName        2
deposit                   0
facing                    0
facingDesc             9431
floor                     0
furnishingDesc            1
gym                       0
id                        0
isMaintenance             0
lift                      0
loanAvailable             0
locality                  2
localityId                0
location                  0
maintenanceAmount         0
ownerName                 0
parking                   0
parkingDesc               1
propertyTitle             0
propertyType              0
property_age              0
reactivationSource       73
rent_amount               0
sharedAccomodation        0
shortUrl                  0
swimmingPool              0
totalFloor                0
type_bhk                  0
waterSupply               0
weight                18900
dtype: int64

In [5]:
data.drop(['weight','combineDescription'],axis=1,inplace=True)

In [6]:
data.to_csv("hyd.csv")